name: Deploy to GitHub Pages
on:
  push:
    branches: [master]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
         npm run build
         touch dist/.nojekyll  # Создает файл, отключающий Jekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Папка, которую генерирует Vite/Vue
          branch: gh-pages # Ветка, из которой GitHub Pages будет брать файлы 
